apiVersion: v1
kind: Pod
metadata:
  name: myboot-ed
spec:
  containers:
    - name: myboot-ed-1
      image: quay.io/rhdevelopers/myboot:v4
      volumeMounts:
        - mountPath: /tmp/demo
          name: my-ed-volume
    - name: myboot-ed-2
      image: quay.io/rhdevelopers/myboot:v4
      env:
        - name: SERVER_PORT
          value: "8081"
      volumeMounts:
        - mountPath: /tmp/demo
          name: my-ed-volume
  volumes:
    - name: my-ed-volume
      emptyDir: {}