[http]
  [http.routers]
    [http.routers.cluster]
      service = "k3s"
      rule = "Host(`10.0.0.30`)"
    [http.routers.Router-1]
      entryPoints = ["dash"]
      rule = "Host(`10.0.0.30`)"
      service = "dashboard"

  [http.services]
    [http.services.k3s]
      [http.services.k3s.loadBalancer]
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://10.0.0.11:6443"
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://10.0.0.12:6443"
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://10.0.0.13:6443"
    [http.services.dashboard]
      [http.services.dashboard.loadBalancer]
        [[http.services.k3s.loadBalancer.servers]]
          url = "https://10.0.0.11:8001"