apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress-session
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "hello-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "hw.med"
    http:
      paths:
      - pathType: Exact
        path: /hello
        backend:
          service:
            name: hello-svc
            port:
              number: 8081
      - pathType: Exact
        path: /world
        backend:
          service:
            name: world-svc
            port:
              number: 8082
