apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cip
  labels:
    system: primary
    app: echo
  namespace: default
spec:
  selector:
    matchLabels:
      system: primary
      app: echo
  replicas: 1
  template:
    metadata:
      labels:
        system: primary
        app: echo
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.8
        imagePullPolicy: Always
        name: echo-service
        env:
        - name: MESSAGE
          value: Hello from ClusterIP!
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeSelector:
        system: node-1

---

apiVersion: v1
kind: Service
metadata:
  name: dep-cip-service
spec:
  selector:
    app: echo
    system: primary
  ports:
    - port: 8080
