apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-np
  labels:
    system: secondary
    app: echo
  namespace: default
spec:
  selector:
    matchLabels:
      system: secondary
      app: echo
  replicas: 1
  template:
    metadata:
      labels:
        system: secondary
        app: echo
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.8
        imagePullPolicy: Always
        name: echo-service
        env:
        - name: MESSAGE
          value: Hello from NodePort!
        ports:
        - containerPort: 8080
          protocol: TCP
      nodeSelector:
        system: node-2

---

apiVersion: v1
kind: Service
metadata:
  name: dep-np-service
spec:
  type: NodePort
  selector:
    app: echo
    system: secondary
  ports:
    - port: 8080

