apiVersion: v1
kind: Pod
metadata:
  labels:
    test: healthcheck
  name: healthcheck-test
spec:
  containers:
  - name: healthcheck-test
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
